### ISSUE TITLE
[1.14.4] Hidden buttons | Crash on click

### ISSUE THREAD

**Issue by TheMCBrothers-Manager** [MrCrayfish/Filters#1]
**Description**
If you open the inventory with a tab open, that has no filters, some buttons don't show up.
When there are zero buttons the game crashes when you click in the button area

**Crash Report:**
https://gist.github.com/TheMCBrothers/ef7026264235e362931bfca14fa7bde1

**Versions**
Forge 28.0.26
Filters 1.1.0

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Filters/commit/561577d6b8c9befded5f71ee0561c74571d6b83a
