### ISSUE TITLE
Is it possible to disable this for certain/problematic mods?

### ISSUE THREAD

**Issue by fuzzyweapon** [MrCrayfish/Filters#3]
I imagine it won't be unusual for mods to have issues that cause this mod to fail, as I just ran into one with DoggyTalents that prevents the server from loading.  Is it possible to disable Filters features for particular mods?

It's a shame to not be able to use this while waiting for mod devs for each active mod to fix issues, but even worse if mod devs decide not to make it compatible with this mod.

**Comment by fuzzyweapon** [comment]
server?  I meant client.

**Comment by fuzzyweapon** [comment]
It would also be acceptable, and probably easier on the user, if it's possible to fail gracefully and keep going.

**Comment by MrCrayfish** [comment]
It seems its not an issue with DoggyTalents but simply my mistake uploading a deobf version of the mod. New version coming soon!
