### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by sepsol** [MrCrayfish/Filters#4]
I've used version 1.0.0 with no problems. When I try to load 1.1.0 (normal or Deobf versions) I get this screen:

![image](https://user-images.githubusercontent.com/47871887/66904709-6fa97e80-f011-11e9-9f90-5a28e91bb718.png)

**Here's the log:**
[latest.log](https://github.com/MrCrayfish/Filters/files/3733397/latest.log)

**Comment by MrCrayfish** [comment]
FIxed in next version
